Capistrano2のrole定義で  `:no_release => true`  オプションを利用できるように変更
mixigroup/server_settings pull request #9
Opened 2017-03-03 06:59 UTC by w1mvy

下記のようにyaml記述することで、 `role :memcached, '192.168.100.1", :no_release => true` という形で定義されるように変更

```
# memcached.yml
memcached:
  no_release: true
  hosts:
    - 192.168.100.1
```

2017-03-03 12:26 UTC, hirocaster requested changes

2017-03-03 12:26 UTC, hirocaster commented on lib/server_settings/host_collection.rb
> +    attr_reader :role_config
capistranoではpropertyという呼び方をしてるので、揃えた方がわかりやすそうですね。
https://github.com/capistrano/capistrano/blob/bf45cbafe5ef396933c81f334bdbc8c6d32a38c2/spec/integration/dsl_spec.rb#L37

2017-03-03 12:26 UTC, hirocaster commented on lib/server_settings/capistrano.rb
> +              if hosts.class == ::ServerSettings::HostCollection && hosts.role_config["%no_release"]
あとはactiveやprimaryぐらいしかないみたいです。
https://github.com/capistrano/capistrano/blob/bf45cbafe5ef396933c81f334bdbc8c6d32a38c2/spec/integration/dsl_spec.rb#L13

この3パターンで分岐して書くか現在のrole_configの値を全部展開してしまっても良いかなと思いました。

2017-03-08 02:22 UTC, w1mvy commented
@hirocaster コメント二件に関して、対応したので再度reviewお願い致します

2017-03-08 05:52 UTC, hirocaster commented on README.md
> +When want to use `no_release` option, described as follow.
せっかく対応したので、`primary`, `active`も記載してみてはどうでしょ?

2017-03-08 06:15 UTC, w1mvy commented
README側も追記致しました

2017-03-09 08:11 UTC, hirocaster approved these changes

2017-03-09 08:11 UTC, merged